[profile.default]
remappings = [
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
